export const questions = [
    "What are your strengths and weaknesses?",
    "How do you typically react to criticism or feedback?",
    "What values are most important to you, and how do they guide your decisions?",
    "Are you aware of your emotions and how they influence your behavior?",
    "What triggers your stress or anxiety, and how do you cope with it?",
    "How do you perceive yourself in comparison to others?",
    "Do you have a clear understanding of your long-term goals and aspirations?",
    "Are you mindful of your thoughts and actions on a daily basis?",
    "What aspects of your personality do you want to improve, and how do you plan to do so?",
    "How do you define success for yourself?",
    "What drives you to pursue your goals and dreams?",
    "How do you maintain motivation during challenging times?",
    "Are you more motivated by internal or external factors?",
    "Do you set specific, achievable goals for yourself? If so, how do you track your progress?",
    "What strategies do you use to overcome procrastination?",
    "Are you motivated by the prospect of rewards or the fear of failure?",
    "How do you stay focused on your priorities amidst distractions?",
    "Have you experienced a significant setback, and how did you bounce back from it?",
    "Do you seek inspiration from others, and if so, who are your role models?",
    "What activities or experiences energize and invigorate you?",
    "How do you define resilience, and how do you cultivate it in your life?",
    "Have you ever faced a seemingly insurmountable obstacle, and how did you overcome it?",
    "What role does self-discipline play in your ability to persevere?",
    "Do you believe in the power of perseverance, even when success seems unlikely?",
    "How do you handle rejection or failure?",
    "Are there specific techniques or practices you use to stay motivated during challenging times?",
    "Have you ever had to make sacrifices to pursue your goals, and if so, what were they?",
    "How do you deal with self-doubt or uncertainty along your journey?",
    "Do you find value in seeking support from others when facing adversity?",
    "What lessons have you learned from past experiences of perseverance?",
    "How do you reflect on your past experiences to inform your future decisions?",
    "Are there patterns in your behavior or thinking that you'd like to change?",
    "What steps do you take to ensure personal growth and development?",
    "How do you balance self-improvement with self-acceptance?",
    "Do you believe in the importance of stepping outside your comfort zone, and if so, how do you do it?",
    "How do you celebrate your achievements and milestones?",
    "Are there areas of your life where you feel stuck or stagnant, and how do you plan to break free from them?",
    "What motivates you to continue evolving and striving for betterment?",
    "How do you stay open to new perspectives and ideas?",
    "What role does self-care play in your overall well-being and success?",
    "How do you make difficult decisions, and what factors do you consider?",
    "Are you accountable for your actions and their consequences?",
    "How do you handle situations where you've made a mistake or poor judgment?",
    "Do you seek feedback from others when making important decisions?",
    "How do you prioritize competing responsibilities and commitments?",
    "Have you ever had to make a tough choice that required sacrificing short-term comfort for long-term gain?",
    "Do you believe in learning from failures, and if so, how do you integrate those lessons into your decision-making process?",
    "How do you ensure that your decisions align with your values and goals?",
    "Are there times when you've had to adjust your plans or goals in response to changing circumstances?",
    "How do you hold yourself accountable for following through on your commitments and goals?"
  ];